// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="SKPhotoBrowser",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC14SKPhotoBrowser13SKCaptionView")
@interface SKCaptionView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
@end



@class UIImage;
@class SKAnimatedImage;

SWIFT_PROTOCOL("_TtP14SKPhotoBrowser15SKPhotoProtocol_")
@protocol SKPhotoProtocol <NSObject>
@property (nonatomic) NSInteger index;
@property (nonatomic) BOOL scrollEnable;
@property (nonatomic, readonly, strong) UIImage * _Nullable underlyingImage;
@property (nonatomic, readonly, strong) SKAnimatedImage * _Nullable underlyingGifImage;
@property (nonatomic, readonly, strong) UIView * _Nullable customView;
@property (nonatomic, readonly, copy) NSString * _Nullable caption;
@property (nonatomic) UIViewContentMode contentMode;
- (void)loadUnderlyingImageAndNotify;
- (BOOL)checkCache SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC14SKPhotoBrowser12SKLocalPhoto")
@interface SKLocalPhoto : NSObject <SKPhotoProtocol>
@property (nonatomic) BOOL scrollEnable;
@property (nonatomic, strong) UIImage * _Nullable underlyingImage;
@property (nonatomic, strong) SKAnimatedImage * _Nullable underlyingGifImage;
@property (nonatomic, strong) UIView * _Nullable customView;
@property (nonatomic) UIViewContentMode contentMode;
@property (nonatomic, copy) NSString * _Nullable caption;
@property (nonatomic) NSInteger index;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (BOOL)checkCache SWIFT_WARN_UNUSED_RESULT;
- (void)loadUnderlyingImageAndNotify;
@end


SWIFT_CLASS("_TtC14SKPhotoBrowser7SKPhoto")
@interface SKPhoto : NSObject <SKPhotoProtocol>
@property (nonatomic) NSInteger index;
@property (nonatomic) BOOL scrollEnable;
@property (nonatomic, strong) UIImage * _Nullable underlyingImage;
@property (nonatomic, strong) SKAnimatedImage * _Nullable underlyingGifImage;
@property (nonatomic, strong) UIView * _Nullable customView;
@property (nonatomic, copy) NSString * _Nullable caption;
@property (nonatomic) UIViewContentMode contentMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (BOOL)checkCache SWIFT_WARN_UNUSED_RESULT;
- (void)loadUnderlyingImageAndNotify;
@end



@class NSBundle;
@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC14SKPhotoBrowser14SKPhotoBrowser")
@interface SKPhotoBrowser : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Null_unspecified)nibNameOrNil bundle:(NSBundle * _Null_unspecified)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)handleSKPhotoLoadingDidEndNotification:(NSNotification * _Nonnull)notification;
@end









@class UIScrollView;

@interface SKPhotoBrowser (SWIFT_EXTENSION(SKPhotoBrowser)) <UIScrollViewDelegate>
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView * _Nonnull)scrollView;
@end



@class NSTimer;

@interface SKPhotoBrowser (SWIFT_EXTENSION(SKPhotoBrowser))
- (void)gotoPreviousPage;
- (void)gotoNextPage;
- (void)hideControls:(NSTimer * _Nonnull)timer;
@end


SWIFT_PROTOCOL("_TtP14SKPhotoBrowser30SKPhotoBrowserAnimatorDelegate_")
@protocol SKPhotoBrowserAnimatorDelegate
- (void)willPresent:(SKPhotoBrowser * _Nonnull)browser;
- (void)willDismiss:(SKPhotoBrowser * _Nonnull)browser;
@end


SWIFT_PROTOCOL("_TtP14SKPhotoBrowser22SKPhotoBrowserDelegate_")
@protocol SKPhotoBrowserDelegate
@optional
/// Tells the delegate that the browser begin dragging scrollView
- (void)scrollViewWillBeginDragging;
/// Tells the delegate that the browser started displaying a new photo
/// \param index the index of the new photo
///
- (void)didShowPhotoAtIndex:(SKPhotoBrowser * _Nonnull)browser index:(NSInteger)index;
/// Tells the delegate the browser will start to dismiss
/// \param index the index of the current photo
///
- (void)willDismissAtPageIndex:(NSInteger)index;
/// Tells the delegate that the browser will start showing the <code>UIActionSheet</code>
/// \param photoIndex the index of the current photo
///
- (void)willShowActionSheet:(NSInteger)photoIndex;
/// Tells the delegate that the browser has been dismissed
/// \param index the index of the current photo
///
- (void)didDismissAtPageIndex:(NSInteger)index;
/// Tells the delegate that the browser did dismiss the UIActionSheet
/// \param buttonIndex the index of the pressed button
///
/// \param photoIndex the index of the current photo
///
- (void)didDismissActionSheetWithButtonIndex:(NSInteger)buttonIndex photoIndex:(NSInteger)photoIndex;
/// Tells the delegate that the browser did scroll to index
/// \param index the index of the photo where the user had scroll
///
- (void)didScrollToIndex:(SKPhotoBrowser * _Nonnull)browser index:(NSInteger)index;
/// Tells the delegate the user removed a photo, when implementing this call, be sure to call reload to finish the deletion process
/// \param browser reference to the calling SKPhotoBrowser
///
/// \param index the index of the removed photo
///
/// \param reload function that needs to be called after finishing syncing up
///
- (void)removePhoto:(SKPhotoBrowser * _Nonnull)browser index:(NSInteger)index reload:(void (^ _Nonnull)(void))reload;
/// Asks the delegate for the view for a certain photo. Needed to detemine the animation when presenting/closing the browser.
/// \param browser reference to the calling SKPhotoBrowser
///
/// \param index the index of the removed photo
///
///
/// returns:
/// the view to animate to
- (UIView * _Nullable)viewForPhoto:(SKPhotoBrowser * _Nonnull)browser index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Tells the delegate that the controls view toggled visibility
/// \param browser reference to the calling SKPhotoBrowser
///
/// \param hidden the status of visibility control
///
- (void)controlsVisibilityToggled:(SKPhotoBrowser * _Nonnull)browser hidden:(BOOL)hidden;
/// Allows  the delegate to create its own caption view
/// \param index the index of the photo
///
- (SKCaptionView * _Nullable)captionViewForPhotoAtIndexWithIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Hanlde single tap on image
- (void)singleTapOnImage;
/// Hanlde direction of scrollview and index
- (void)didScrollDirectionWithIsLeft:(BOOL)isLeft index:(NSInteger)index;
/// Hanlde pan gesture with offet Y
- (void)didPanGestureRecognizedWithOffsetY:(CGFloat)offsetY;
@end



SWIFT_CLASS("_TtC14SKPhotoBrowser19SKZoomingScrollView")
@interface SKZoomingScrollView : UIScrollView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
@end








@interface SKZoomingScrollView (SWIFT_EXTENSION(SKPhotoBrowser)) <UIScrollViewDelegate>
- (UIView * _Nullable)viewForZoomingInScrollView:(UIScrollView * _Nonnull)scrollView SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginZooming:(UIScrollView * _Nonnull)scrollView withView:(UIView * _Nullable)view;
- (void)scrollViewDidZoom:(UIScrollView * _Nonnull)scrollView;
@end











#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
